## 設定ファイルのバージョンです。変更しないでください。
version: 1

## メッセージ関係の設定
### メッセージを流すかどうか...各機能のmessageをtrueで流す、falseで流さない

## 制限を適用しない例外ワールドの設定
IgnoreWorlds:
  - "ENTER"
  - "IGNORE"
  - "WORLD's"
  - "NAME"

## 着火関係の設定
### この設定をfalseに変えると個別に設定した要因以外では着火を許可します。
### messageをfalseにするとメッセージは流れなくなります。
RestrictIgnite: true
  message: true
  content: "ブロックへの着火をキャンセルしました！"
### 個別の着火要因による制限
#### 火打ち石による着火を制限
ByFlintAndSteel: true
#### 延焼による着火を制限
ByFireSpread: true
#### マグマによる着火を制限
ByLava: true
#### 雷による着火の制限
ByLightning: true
#### ファイアーボールによる着火の制限
ByFireBall: true
#### 爆発による着火の制限
ByExplosion: true

## 爆発の制限
### messageをfalseにするとメッセージは流れなくなります。
CancelExplosion: true
  message: true
  content: "爆発をキャンセルしました！"

## バケツによる設置の制限
### この設定をfalseに変えると個別に設定した内容次第では許可するようになります。
### messageをfalseにするとメッセージは流れなくなります。
RestrictUsingBucket: true
  message: true
  content: "液体の設置をキャンセルしました！"
### 個別の設定
### マグマ
RestrictUsingLavaBucket: true
### 水
RestrictUsingWatarBucket: true

## 水・マグマブロックの設置の制限
### この設定をfalseに変えると個別に設定した内容次第では許可するようになります。
### messageをfalseにするとメッセージは流れなくなります。
RestrictPlace: true
  message: true
  content: "液体プロックの設置をキャンセルしました！"
### 個別の設定
### マグマ
RestrictPlaceLava: true
### 水
RestrictPlaceWatar: true

## 水・マグマの流れを制限
### この設定をfalseに変えると個別に設定した内容次第では許可するようになります。
### messageをfalseにするとメッセージは流れなくなります。
RestrictFlow: true
  message: true
  content: "液体の流出をキャンセルしました！"
### 個別の設定
### マグマ
RestrictFlowLava: true
### 水
RestrictFlowWatar: true